shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.ohmyzsh-lib-git]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["git.zsh"]

[plugins.ohmyzsh-plugin-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.ohmyzsh-plugin-1password]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/1password"
