#!/usr/bin/env zsh

# De-duplicate PATH array
typeset -U path

# Basic PATH prepending (user local bin)
path=($HOME/.local/bin $path)

# Ovveride HISTFILE from environment.d
export HISTFILE="$ZDOTDIR/.zsh_history"
