# Merges default lazygit config with one generated by matugen
# Lazygit fails to launch if the config file doesn't exist, so we avoid setting the variable in that case

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/lazygit/matugen-theme.yml" ]; then
  export LG_CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/lazygit/config.yml,${XDG_CONFIG_HOME:-$HOME/.config}/lazygit/matugen-theme.yml"
fi
